# Copyright (c) 2018-2022 Morwenn
# SPDX-License-Identifier: MIT

coverage:
  ignore:
    - "tests"
    # This unrolled version of a merge-insertion sort derivative was tested
    # exhaustively for every permutation of an integer sequence of 9 elements,
    # thus we don't include it
    - "include/cpp-sort/detail/low_comparisons/sort9.h"
    # Sorting networks have been tested independently with the 0-1 principle
    # when needed, so we do not need to test them exhaustively in the test
    # suite
    - "include/cpp-sort/detail/sorting_network/*"
