# Copyright (c) 2026 Morwenn
# SPDX-License-Identifier: MIT

name: Wiki Deployment

on:
  push:
    branches:
      - trunk
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  sync-wiki-files:
    name: Sync Wiki Files

    runs-on: codeberg-tiny-lazy

    steps:
      - name: Checkout /docs
        uses: actions/checkout@v6
        with:
          repository: ${{forgejo.repository}}
          path: main

      - name: Checkout wiki
        uses: actions/checkout@v6
        with:
          repository: ${{forgejo.repository}}.wiki
          path: wiki

      - name: Sync wiki files
        run: |
          apt-get update
          apt-get install -y rsync
          for docname in main/docs/*.md; do
            old=$(basename "$docname");
            new=${old%.*};
            find main/docs -name "*.md" -exec sed -i "s/$old/$new/g" {} \;
          done
          rsync -avzr --delete --exclude='.git/' "main/docs/" "wiki/"

      - name: Commit changes
        working-directory: wiki
        run: |
          git config --local user.email "action@forgejo.org"
          git config --local user.name "Forgejo Action"
          git add .
          git commit -m "Synchronize wiki with docs/"

      - name: Push changes to wiki
        working-directory: wiki
        run: |
          git push
