/*
 * Copyright (c) 2025 Morwenn
 * SPDX-License-Identifier: MIT
 */
#include <algorithm>
#include <deque>
#include <forward_list>
#include <list>
#include <vector>
#include <catch2/catch_template_test_macros.hpp>
#include <rapidcheck.h>
#include <rapidcheck/catch.h>
#include <cpp-sort/sorters.h>
#include <cpp-sort/utility/buffer.h>
#include <cpp-sort/utility/functional.h>
#include <testing-tools/old_sorters.h>

TEMPLATE_TEST_CASE( "test random-access sorters with distributions generated by RapidCheck", "[distributions]",
                    cppsort::adaptive_shivers_sorter,
                    cppsort::cartesian_tree_sorter,
                    cppsort::d_ary_heap_sorter<2>,
                    cppsort::d_ary_heap_sorter<3>,
                    cppsort::d_ary_heap_sorter<4>,
                    cppsort::d_ary_heap_sorter<5>,
                    cppsort::d_ary_heap_sorter<6>,
                    cppsort::d_ary_heap_sorter<7>,
                    cppsort::d_ary_heap_sorter<8>,
                    cppsort::d_ary_heap_sorter<9>,
                    old_drop_merge_sorter,
                    cppsort::grail_sorter<>,
                    cppsort::grail_sorter<
                        cppsort::utility::dynamic_buffer<cppsort::utility::sqrt>
                    >,
                    cppsort::heap_sorter,
                    cppsort::insertion_sorter,
                    cppsort::mel_sorter,
                    cppsort::merge_sorter,
                    cppsort::merge_insertion_sorter,
                    cppsort::pdq_sorter,
                    cppsort::poplar_sorter,
                    cppsort::quick_merge_sorter,
                    cppsort::quick_sorter,
                    cppsort::selection_sorter,
                    cppsort::ska_sorter,
                    cppsort::slab_sorter,
                    cppsort::smooth_sorter,
                    cppsort::spin_sorter,
                    cppsort::splay_sorter,
                    old_split_sorter,
                    cppsort::spread_sorter,
                    cppsort::std_sorter,
                    cppsort::tim_sorter,
                    old_verge_sorter,
                    cppsort::wiki_sorter<>,
                    cppsort::wiki_sorter<
                        cppsort::utility::dynamic_buffer<cppsort::utility::half>
                    > )
{
    TestType sorter;

    rc::prop("with std::vector", [sorter](std::vector<int> collection) {
        auto copy = collection;

        sorter(collection);
        bool res = std::is_sorted(collection.begin(), collection.end());

        cppsort::pdq_sort(copy);
        return res && collection == copy;
    });

    rc::prop("with std::deque", [sorter](std::deque<int> collection) {
        auto copy = collection;

        sorter(collection);
        bool res = std::is_sorted(collection.begin(), collection.end());

        cppsort::pdq_sort(copy);
        return res && collection == copy;
    });
}

TEMPLATE_TEST_CASE( "test bidirectional sorters with distributions generated by RapidCheck", "[distributions]",
                    cppsort::cartesian_tree_sorter,
                    old_drop_merge_sorter,
                    cppsort::insertion_sorter,
                    cppsort::mel_sorter,
                    cppsort::merge_sorter,
                    cppsort::quick_merge_sorter,
                    cppsort::quick_sorter,
                    cppsort::selection_sorter,
                    cppsort::slab_sorter,
                    cppsort::splay_sorter,
                    old_verge_sorter )
{
    TestType sorter;

    rc::prop("with std::list", [sorter](std::list<int> collection) {
        auto copy = collection;

        sorter(collection);
        bool res = std::is_sorted(collection.begin(), collection.end());

        cppsort::merge_sort(copy);
        return res && collection == copy;
    });
}

TEMPLATE_TEST_CASE( "test forward sorters with distributions generated by RapidCheck", "[distributions]",
                    cppsort::cartesian_tree_sorter,
                    cppsort::mel_sorter,
                    cppsort::merge_sorter,
                    cppsort::quick_merge_sorter,
                    cppsort::quick_sorter,
                    cppsort::selection_sorter,
                    cppsort::splay_sorter )
{
    TestType sorter;

    rc::prop("with std::forward_list", [sorter](std::forward_list<int> collection) {
        auto copy = collection;

        sorter(collection);
        bool res = std::is_sorted(collection.begin(), collection.end());

        cppsort::merge_sort(copy);
        return res && collection == copy;
    });
}
