# Copyright (c) 2021-2024 Morwenn
# SPDX-License-Identifier: MIT

name: MSVC Builds

on:
  push:
    paths:
      - '.github/workflows/build-msvc.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'examples/**'
      - 'include/**'
      - 'tests/**'
  pull_request:
    paths:
      - '.github/workflows/build-msvc.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'examples/**'
      - 'include/**'
      - 'tests/**'

jobs:
  build:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        config:
        - build_type: Release
        - build_type: Debug
        - build_type: Debug
          build_tools: '-T ClangCL'

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        shell: pwsh
        working-directory: ${{runner.workspace}}
        run: |
          cmake -H${{github.event.repository.name}} -Bbuild `
                -DCMAKE_CONFIGURATION_TYPES=${{matrix.config.build_type}} `
                -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} `
                -G"Visual Studio 17 2022" -A x64 ${{matrix.config.build_tools}} `
                -DCPPSORT_BUILD_EXAMPLES=ON

      - name: Build the test suite
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.config.build_type}}

      - name: Run the test suite
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        working-directory: ${{runner.workspace}}/build
        run: ctest -C ${{matrix.config.build_type}} --no-tests=error
