# Copyright (c) 2021-2022 Morwenn
# SPDX-License-Identifier: MIT

name: MSVC Builds

on:
  push:
    paths:
      - '.github/workflows/build-msvc.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'examples/**'
      - 'include/**'
      - 'tests/**'
  pull_request:
    paths:
      - '.github/workflows/build-msvc.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'examples/**'
      - 'include/**'
      - 'tests/**'

jobs:
  build:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        shell: pwsh
        working-directory: ${{runner.workspace}}
        run: |
          cmake -H${{github.event.repository.name}} -Bbuild `
                -DCMAKE_CONFIGURATION_TYPES=${{matrix.build_type}} `
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}} `
                -G"Visual Studio 16 2019" -A x64 `
                -DCPPSORT_BUILD_EXAMPLES=ON

      - name: Build the test suite
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}} -j 2

      - name: Run the test suite
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        working-directory: ${{runner.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --no-tests=error
